# Why Numpy?

NumPy is built in C language because C is faster while Python is slower. On the other hand, syntax of Python is easier to learn and hence it became very famous among users (especially non-programming or developer).

Pandas, matplotlib, etc. are then built on NumPy. This made Numpy an excellency choice for Data Science field.

# Numpy Array vs Python Sequences

1. NumPy arrays have fixed size at creation, unlike Python lists (which can grow dynamically). If you change size of an ndarray it will create a new array and delete the original one.

2. NumPy array have one datatype, i.e. Homegenous, while lists are heterogeneous and can contain different datatypes. 

Note: Python lists are able to store different types of data because they store pointers (addresses) to the actual data rather than the data itself. This allows lists to be flexible and store various types of data. However, this means that they require more memory and are slower for numerical operations compared to NumPy arrays, which store data in a contiguous block of memory and are optimized for performance.

3. NumPy arrays are more compact than lists, which means they use less memory to store data. This is because NumPy arrays are stored in a contiguous block of memory, while lists store pointers to the actual data.

4. NumPy arrays are faster than lists for numerical operations because they are optimized for performance and use less memory. This is because NumPy arrays are implemented in C and use optimized algorithms for numerical operations, while lists are implemented in Python and are not optimized for performance.

5. NumPy arrays have a wide range of built-in functions and methods for performing mathematical operations, while lists do not have as many built-in functions for numerical operations. This makes NumPy arrays more convenient for scientific computing and data analysis tasks.

6. NumPy arrays support vectorized operations, which means you can perform element-wise operations on entire arrays without the need for explicit loops. This allows for more efficient and concise code when performing mathematical operations on large datasets.

7. NumPy arrays can be multi-dimensional, allowing for the creation of matrices and higher-dimensional arrays, while Python lists are typically one-dimensional (though they can contain other lists to create multi-dimensional structures, it is not as efficient or convenient as using NumPy arrays).

8. NumPy arrays have a fixed size at creation, while Python lists can grow dynamically. If you change the size of a NumPy array, it will create a new array and delete the original one, while Python lists can simply append or remove elements without creating a new list.

9. A growing number of libraries and frameworks in the scientific computing and data science ecosystem are built on top of NumPy, making it a fundamental tool for many applications in these fields. This widespread adoption has further solidified NumPy's position as a key component of the Python scientific computing stack.


In [1]:
# import libraries

# np = numerical python

# np is just a shortform for numpy library
 

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
# create list of numbers in NumPy array

# this is a 1D array, i.e. one dimensional array

array_1D = np.array([1,2,3,4,5,6,7,8,9,10])

print(array_1D)
print(type(array_1D))


[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


1. The type of the array says <class 'numpy.ndarray'>

2. Class is a blueprint for creating objects. This is a famous concept in object-oriented programming (OOP). 

3. Python is an object-oriented programming language, which means that it allows you to create and use objects.

4. Everything in Python is an object, including functions, classes, and even modules.

# Types of Numerical Data Structures

Scalar  = one number
Vector  = list of numbers
Matrix  = table of numbers
Tensor  = any higher-dimensional collection of numbers including 3D

0D → Scalar
1D → Vector
2D → Matrix
3D+ → Tensor

In [3]:
# let us create a 2D array, i.e. two dimensional array such as a matrix

array_2D = np.array([[100,101],
                     [102,103],
                     [104,105],
                     [106,107],
                     [108,109]
                     ]) 

print(array_2D)
print(type(array_2D))
print(array_2D.shape) # this will give us the shape of the array, i.e. number of rows and columns


[[100 101]
 [102 103]
 [104 105]
 [106 107]
 [108 109]]
<class 'numpy.ndarray'>
(5, 2)


In [4]:
# let us create a 3D array, i.e. three dimensional array such as a tensor.

# Tensor is a generalization of matrices to higher dimensions. It is a multi-dimensional array.

array_3D = np.array([
                    [
                        [1000,2000],
                        [1500,2500]
                    ],
                    [
                        [4000,5000],
                        [4500,5500]     
                    ],
                    [
                        [6000,7000],
                        [6500,7500]
                    ]
                    ])

print(array_3D)
print(type(array_3D))
print(array_3D.shape) 


[[[1000 2000]
  [1500 2500]]

 [[4000 5000]
  [4500 5500]]

 [[6000 7000]
  [6500 7500]]]
<class 'numpy.ndarray'>
(3, 2, 2)


In [5]:
# Float or any other data type can be specified while creating the array. 

array_float = np.array([1,2,3,4,5], dtype=float)

print(array_float)
print(type(array_float))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


In [6]:
# Boolean data type can also be specified while creating the array.

array_bool_1 = np.array([1,0,2,0,-1], dtype=bool)      

# the value must be either 0 or 1? No, any non-zero value (e.g. 2, -1, 1000, etc.) will be considered as True and zero will be considered as False.

print(array_bool_1)
print(type(array_bool_1))

[ True False  True False  True]
<class 'numpy.ndarray'>


In [7]:
# let us see boolean array by using True or False values only.

array_bool_2 = np.array([True, False, True, False, True], dtype=bool)
print(array_bool_2)
print(type(array_bool_2))

[ True False  True False  True]
<class 'numpy.ndarray'>


In [8]:
# let us see boolean array by using values other than True or False or 1 or 1

array_bool_3 = np.array(['Arsalan', 5, "e", -1, True, 0, 0.0, False,"", None], dtype=bool)
print(array_bool_3)
print(type(array_bool_3))

# Conclusion: Python converts values to boolean using truthiness rules.

# Values considered False:

# 1. 0
# 2. 0.0
# 3. False
# 4. Empty string ""
# 5. Empty containers such as [], (), {}, set()
# 6. None

# Most other values are considered True.


[ True  True  True  True  True False False False False False]
<class 'numpy.ndarray'>


In [9]:
# [],{},set(),(). - these cannot be tested for boolean values as they are empty containers, not scalar values.

# [], {}, set(), and () are collections, not simple scalar values, so NumPy gets confused when forcing everything into one clean boolean array.

bool_list = bool([]) # this to see whether this container (list) is True or False. It will return False as it is an empty container.

print(bool_list)
print(type(bool_list))

False
<class 'bool'>


In [10]:
bool_dict = bool({}) # this to see whether this container (dictionary) is True or False. It will return False as it is an empty container.
print(bool_dict)
print(type(bool_dict))

False
<class 'bool'>


In [11]:
bool_set = bool(set()) # this to see whether this container (set) is True or False. It will return False as it is an empty container.
print(bool_set)
print(type(bool_set))

False
<class 'bool'>


In [12]:
bool_tuple = bool(()) # this to see whether this container (tuple) is True or False. It will return False as it is an empty container.
print(bool_tuple)
print(type(bool_tuple))

False
<class 'bool'>


In [13]:
# range(0) also returns False as it is an empty container.

print(bool(range(0)))
print(type(bool(range(0))))

False
<class 'bool'>


# Summary: 

In Python, empty containers (list, dictionary, set(), range(), and tuple) are considered False when converted to boolean values.

Other than empty containers, we saw 0, 0.0, False, empty string "", and None are also considered False when converted to boolean values.

Almost everything else is considered True when converted to boolean values including 1, -1, 2, -2, 1000, -1000, "Arsalan", "e", " ", etc. 

The last one is a space character, it is a non-empty string, which is also considered True when converted to boolean values.


# Data types for NumPy arrays

Other than float and boolean data types for arrays we can also specify other data types such as:
1. int
2. complex 
3. str

Other NumPy data types include:

4. bool
5. object
6. complex64, complex128
7. datetime64
8. timedelta64
9. int8, int16, int32, int64
10. uint8, uint16, uint32, uint64
11. float16, float32, float64

There are some more data types in NumPy but these are the most commonly used data types. 

The complete list of data types can be found in the official documentation of NumPy.

In [14]:
# now we study np.arange() function
# It isused to create an array of evenly spaced values within a given interval. 
# It is similar to the built-in range() function but returns an array instead of a list.

array_arange1 = np.arange(100,110)
print(array_arange1)
print(type(array_arange1))

# Very important note: the last value (stop value) is not included in the array, it is exclusive. 
# So the array will include values from 100 to 109 only, not 110.
# This is same as the built-in range() function in Python, where the stop value is also exclusive.

array_arange2 = np.arange(50,55)    # this will print 50, 51, 52, 53, and 54 only, not 55.
print(array_arange2)
print(type(array_arange2))

[100 101 102 103 104 105 106 107 108 109]
<class 'numpy.ndarray'>
[50 51 52 53 54]
<class 'numpy.ndarray'>


In [15]:
# STEPS in np.arange() function
# In other words, strides is the step size between values in the array. 
# It is an optional argument that can be specified to create an array with a specific step size.

# np.arange(start, stop, step)

# e.g. print even number between 0 and 10 by using np.arange()

np.arange(0, 10, 2) # this will print 0, 2, 4, 6, and 8 only, not 10. The step size is 2.

array([0, 2, 4, 6, 8])

In [16]:
# print even numbers from 0 to infinity by using np.arange(). 
# However, this will not work as it will end up in an infinite loop and will consume all the memory of the computer. 
# So we should avoid using np.arange() with infinity as stop value.  

# np.arange(0, np.inf, 2) # this will print even numbers from 0 to infinity. The step size is 2. 

# The stop value is infinity, so it will keep generating even numbers indefinitely.

In [17]:
# print table of 5 by using np.arange()

np.arange(0, 51, 5) # this will print 0, 5, 10, 15, 20, 25, 30, 35, 40, and 45 only, not 50. The step size is 5.

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [25]:
# reshape() function is used to change the shape of an array without changing its data.
# It takes a tuple as an argument which specifies the new shape of the array.

array_reshaped = np.arange(100,2000,200).reshape(10,1) 

# this will print 100, 200, 300, ..., 1900 only, not 2000. The step size is 200.
# the reshape() function will change the shape of the array to 10 rows and 1 column.

print(array_reshaped)
print(type(array_reshaped))


[[ 100]
 [ 300]
 [ 500]
 [ 700]
 [ 900]
 [1100]
 [1300]
 [1500]
 [1700]
 [1900]]
<class 'numpy.ndarray'>


In [ ]:
# np.ones() function is used to create an array of ones with a specified shape and data type.

np.ones((5,5)) 

# this will create a 5x5 array of ones. 
# The shape of the array is (5,5) and the data type is float by default.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.ones((3,4), dtype=int) # this will create a 3x4 array of ones with integer data type.

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.ones((4,4), dtype=bool) 

# this will create a 4x4 array of ones with boolean data type. 
# The value will be True as it is non-zero value.

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# np.zeros() function is used to create an array of zeros with a specified shape and data type.

# default data type is float, so it will create an array of zeros with float data type.

np.zeros((5,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros((3,3), dtype=int) # this will create a 3x3 array of zeros with integer data type.

# this will create a 3x3 array of zeros with the default float data type.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [33]:
# np.random.rand() function is used to create an array of random numbers between 0 and 1 with a specified shape.

np.random.rand(3,4) 

# this will create a 3x4 array of random numbers between 0 and 1. The shape of the array is (3,4).

# Why between 0 and 1? 
#
# Because the np.random.rand() function generates random numbers from a uniform distribution over [0, 1).

array([[0.01676819, 0.80513558, 0.66054626, 0.38840401],
       [0.88815955, 0.01637669, 0.33991246, 0.41069147],
       [0.15561102, 0.14157549, 0.52063318, 0.84385001]])

In [42]:
np.random.random((2,3)) 

# this will create a 2x3 array of random numbers between 0 and 1. The shape of the array is (2,3).

# this is same as np.random.rand(2,3) function. Both functions generate random numbers between 0 and 1. 


array([[0.3906987 , 0.8280287 , 0.91797006],
       [0.13730184, 0.48582788, 0.52963464]])

In [36]:
# np.linspace() function is used to create an array of evenly spaced numbers over a specified interval.

# linspace is a short form of linear space. 

# It is used to create an array of evenly spaced numbers over a specified interval.

# format is np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

# the 'Stop' value is inclusive by default 

# but it can be made exclusive by setting the 'endpoint' parameter to False.

np.linspace(100, 200, num=5) 

# this will create an array of 5 evenly spaced numbers between 100 and 200. 


array([100., 125., 150., 175., 200.])

In [40]:
np.linspace(-10,10, num=5)

array([-10.,  -5.,   0.,   5.,  10.])

In [ ]:
# np.identity() function is used to create an identity matrix of a specified size.

np.identity(8) # this will create an 8x8 identity matrix. The shape of the array is (8,8).

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
np.identity(5, dtype=int) 
# this will create a 5x5 identity matrix with integer data type. The shape of the array is (5,5).

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Numpy Attributes

In [1]:
# ndim 

# Thi

In [ ]:
# shape

In [ ]:
# size 

In [ ]:
# itemsize

In [ ]:
# dtype 

Studied until min 34