# Why Numpy?

NumPy is built in C language because C is faster while Python is slower. On the other hand, syntax of Python is easier to learn and hence it became very famous among users (especially non-programming or developer).

Pandas, matplotlib, etc. are then built on NumPy. This made Numpy an excellency choice for Data Science field.

# Numpy Array vs Python Sequences

1. NumPy arrays have fixed size at creation, unlike Python lists (which can grow dynamically). If you change size of an ndarray it will create a new array and delete the original one.

2. NumPy array have one datatype, i.e. Homegenous, while lists are heterogeneous and can contain different datatypes. 

Note: Python lists are able to store different types of data because they store pointers (addresses) to the actual data rather than the data itself. This allows lists to be flexible and store various types of data. However, this means that they require more memory and are slower for numerical operations compared to NumPy arrays, which store data in a contiguous block of memory and are optimized for performance.

3. NumPy arrays are more compact than lists, which means they use less memory to store data. This is because NumPy arrays are stored in a contiguous block of memory, while lists store pointers to the actual data.

4. NumPy arrays are faster than lists for numerical operations because they are optimized for performance and use less memory. This is because NumPy arrays are implemented in C and use optimized algorithms for numerical operations, while lists are implemented in Python and are not optimized for performance.

5. NumPy arrays have a wide range of built-in functions and methods for performing mathematical operations, while lists do not have as many built-in functions for numerical operations. This makes NumPy arrays more convenient for scientific computing and data analysis tasks.

6. NumPy arrays support vectorized operations, which means you can perform element-wise operations on entire arrays without the need for explicit loops. This allows for more efficient and concise code when performing mathematical operations on large datasets.

7. NumPy arrays can be multi-dimensional, allowing for the creation of matrices and higher-dimensional arrays, while Python lists are typically one-dimensional (though they can contain other lists to create multi-dimensional structures, it is not as efficient or convenient as using NumPy arrays).

8. NumPy arrays have a fixed size at creation, while Python lists can grow dynamically. If you change the size of a NumPy array, it will create a new array and delete the original one, while Python lists can simply append or remove elements without creating a new list.

9. A growing number of libraries and frameworks in the scientific computing and data science ecosystem are built on top of NumPy, making it a fundamental tool for many applications in these fields. This widespread adoption has further solidified NumPy's position as a key component of the Python scientific computing stack.


In [1]:
# import libraries

# np = numerical python

# np is just a shortform for numpy library
 

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
# create list of numbers in NumPy array

# this is a 1D array, i.e. one dimensional array

array_1D = np.array([1,2,3,4,5,6,7,8,9,10])

print(array_1D)
print(type(array_1D))


[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


1. The type of the array says <class 'numpy.ndarray'>

2. Class is a blueprint for creating objects. This is a famous concept in object-oriented programming (OOP). 

3. Python is an object-oriented programming language, which means that it allows you to create and use objects.

4. Everything in Python is an object, including functions, classes, and even modules.

# Types of Numerical Data Structures

Scalar  = one number
Vector  = list of numbers
Matrix  = table of numbers
Tensor  = any higher-dimensional collection of numbers including 3D

0D → Scalar
1D → Vector
2D → Matrix
3D+ → Tensor

In [3]:
# let us create a 2D array, i.e. two dimensional array such as a matrix

array_2D = np.array([[100,101],
                     [102,103],
                     [104,105],
                     [106,107],
                     [108,109]
                     ]) 

print(array_2D)
print(type(array_2D))
print(array_2D.shape) # this will give us the shape of the array, i.e. number of rows and columns


[[100 101]
 [102 103]
 [104 105]
 [106 107]
 [108 109]]
<class 'numpy.ndarray'>
(5, 2)


In [4]:
# let us create a 3D array, i.e. three dimensional array such as a tensor.

# Tensor is a generalization of matrices to higher dimensions. It is a multi-dimensional array.

array_3D = np.array([
                    [
                        [1000,2000],
                        [1500,2500]
                    ],
                    [
                        [4000,5000],
                        [4500,5500]     
                    ],
                    [
                        [6000,7000],
                        [6500,7500]
                    ]
                    ])

print(array_3D)
print(type(array_3D))
print(array_3D.shape) 


[[[1000 2000]
  [1500 2500]]

 [[4000 5000]
  [4500 5500]]

 [[6000 7000]
  [6500 7500]]]
<class 'numpy.ndarray'>
(3, 2, 2)


In [5]:
# Float or any other data type can be specified while creating the array. 

array_float = np.array([1,2,3,4,5], dtype=float)

print(array_float)
print(type(array_float))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


In [6]:
# Boolean data type can also be specified while creating the array.

array_bool_1 = np.array([1,0,2,0,-1], dtype=bool)      

# the value must be either 0 or 1? No, any non-zero value (e.g. 2, -1, 1000, etc.) will be considered as True and zero will be considered as False.

print(array_bool_1)
print(type(array_bool_1))

[ True False  True False  True]
<class 'numpy.ndarray'>


In [7]:
# let us see boolean array by using True or False values only.

array_bool_2 = np.array([True, False, True, False, True], dtype=bool)
print(array_bool_2)
print(type(array_bool_2))

[ True False  True False  True]
<class 'numpy.ndarray'>


In [8]:
# let us see boolean array by using values other than True or False or 1 or 1

array_bool_3 = np.array(['Arsalan', 5, "e", -1, True, 0, 0.0, False,"", None], dtype=bool)
print(array_bool_3)
print(type(array_bool_3))

# Conclusion: Python converts values to boolean using truthiness rules.

# Values considered False:

# 1. 0
# 2. 0.0
# 3. False
# 4. Empty string ""
# 5. Empty containers such as [], (), {}, set()
# 6. None

# Most other values are considered True.


[ True  True  True  True  True False False False False False]
<class 'numpy.ndarray'>


In [9]:
# [],{},set(),(). - these cannot be tested for boolean values as they are empty containers, not scalar values.

# [], {}, set(), and () are collections, not simple scalar values, so NumPy gets confused when forcing everything into one clean boolean array.

bool_list = bool([]) # this to see whether this container (list) is True or False. It will return False as it is an empty container.

print(bool_list)
print(type(bool_list))

False
<class 'bool'>


In [10]:
bool_dict = bool({}) # this to see whether this container (dictionary) is True or False. It will return False as it is an empty container.
print(bool_dict)
print(type(bool_dict))

False
<class 'bool'>


In [11]:
bool_set = bool(set()) # this to see whether this container (set) is True or False. It will return False as it is an empty container.
print(bool_set)
print(type(bool_set))

False
<class 'bool'>


In [12]:
bool_tuple = bool(()) # this to see whether this container (tuple) is True or False. It will return False as it is an empty container.
print(bool_tuple)
print(type(bool_tuple))

False
<class 'bool'>


In [13]:
# range(0) also returns False as it is an empty container.

print(bool(range(0)))
print(type(bool(range(0))))

False
<class 'bool'>


# Summary: 

In Python, empty containers (list, dictionary, set(), range(), and tuple) are considered False when converted to boolean values.

Other than empty containers, we saw 0, 0.0, False, empty string "", and None are also considered False when converted to boolean values.

Almost everything else is considered True when converted to boolean values including 1, -1, 2, -2, 1000, -1000, "Arsalan", "e", " ", etc. 

The last one is a space character, it is a non-empty string, which is also considered True when converted to boolean values.


# Data types for NumPy arrays

Other than float and boolean data types for arrays we can also specify other data types such as:
1. int
2. complex 
3. str

Other NumPy data types include:

4. bool
5. object
6. complex64, complex128
7. datetime64
8. timedelta64
9. int8, int16, int32, int64
10. uint8, uint16, uint32, uint64
11. float16, float32, float64

There are some more data types in NumPy but these are the most commonly used data types. 

The complete list of data types can be found in the official documentation of NumPy.

In [14]:
# now we study np.arange() function
# It isused to create an array of evenly spaced values within a given interval. 
# It is similar to the built-in range() function but returns an array instead of a list.

array_arange1 = np.arange(100,110)
print(array_arange1)
print(type(array_arange1))

# Very important note: the last value (stop value) is not included in the array, it is exclusive. 
# So the array will include values from 100 to 109 only, not 110.
# This is same as the built-in range() function in Python, where the stop value is also exclusive.

array_arange2 = np.arange(50,55)    # this will print 50, 51, 52, 53, and 54 only, not 55.
print(array_arange2)
print(type(array_arange2))

[100 101 102 103 104 105 106 107 108 109]
<class 'numpy.ndarray'>
[50 51 52 53 54]
<class 'numpy.ndarray'>


In [15]:
# STEPS in np.arange() function
# In other words, strides is the step size between values in the array. 
# It is an optional argument that can be specified to create an array with a specific step size.

# np.arange(start, stop, step)

# e.g. print even number between 0 and 10 by using np.arange()

np.arange(0, 10, 2) # this will print 0, 2, 4, 6, and 8 only, not 10. The step size is 2.

array([0, 2, 4, 6, 8])

In [16]:
# print even numbers from 0 to infinity by using np.arange(). 
# However, this will not work as it will end up in an infinite loop and will consume all the memory of the computer. 
# So we should avoid using np.arange() with infinity as stop value.  

# np.arange(0, np.inf, 2) # this will print even numbers from 0 to infinity. The step size is 2. 

# The stop value is infinity, so it will keep generating even numbers indefinitely.

In [17]:
# print table of 5 by using np.arange()

np.arange(0, 51, 5) # this will print 0, 5, 10, 15, 20, 25, 30, 35, 40, and 45 only, not 50. The step size is 5.

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
# reshape() function is used to change the shape of an array without changing its data.
# It takes a tuple as an argument which specifies the new shape of the array.

array_reshaped = np.arange(100,2000,200).reshape(10,1) 

# this will print 100, 200, 300, ..., 1900 only, not 2000. The step size is 200.
# the reshape() function will change the shape of the array to 10 rows and 1 column.

print(array_reshaped)
print(type(array_reshaped))


[[ 100]
 [ 300]
 [ 500]
 [ 700]
 [ 900]
 [1100]
 [1300]
 [1500]
 [1700]
 [1900]]
<class 'numpy.ndarray'>


In [19]:
# np.ones() function is used to create an array of ones with a specified shape and data type.

np.ones((5,5)) 

# this will create a 5x5 array of ones. 
# The shape of the array is (5,5) and the data type is float by default.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((3,4), dtype=int) # this will create a 3x4 array of ones with integer data type.

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.ones((4,4), dtype=bool) 

# this will create a 4x4 array of ones with boolean data type. 
# The value will be True as it is non-zero value.

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
# np.zeros() function is used to create an array of zeros with a specified shape and data type.

# default data type is float, so it will create an array of zeros with float data type.

np.zeros((5,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros((3,3), dtype=int) # this will create a 3x3 array of zeros with integer data type.

# this will create a 3x3 array of zeros with the default float data type.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
# np.random.rand() function is used to create an array of random numbers between 0 and 1 with a specified shape.

np.random.rand(3,4) 

# this will create a 3x4 array of random numbers between 0 and 1. The shape of the array is (3,4).

# Why between 0 and 1? 
#
# Because the np.random.rand() function generates random numbers from a uniform distribution over [0, 1).

array([[0.54628075, 0.85640829, 0.70898935, 0.69027958],
       [0.37468989, 0.77404955, 0.46306036, 0.67646619],
       [0.99251964, 0.77715259, 0.69104799, 0.67542214]])

In [25]:
np.random.random((2,3)) 

# this will create a 2x3 array of random numbers between 0 and 1. The shape of the array is (2,3).

# this is same as np.random.rand(2,3) function. Both functions generate random numbers between 0 and 1. 


array([[0.69740149, 0.24733058, 0.75718805],
       [0.30348   , 0.26419333, 0.08143852]])

In [26]:
# np.linspace() function is used to create an array of evenly spaced numbers over a specified interval.

# linspace is a short form of linear space. 

# It is used to create an array of evenly spaced numbers over a specified interval.

# format is np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

# the 'Stop' value is inclusive by default 

# but it can be made exclusive by setting the 'endpoint' parameter to False.

np.linspace(100, 200, num=5) 

# this will create an array of 5 evenly spaced numbers between 100 and 200. 


array([100., 125., 150., 175., 200.])

In [27]:
np.linspace(-10,10, num=5)

array([-10.,  -5.,   0.,   5.,  10.])

In [28]:
# np.identity() function is used to create an identity matrix of a specified size.

np.identity(8) # this will create an 8x8 identity matrix. The shape of the array is (8,8).

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
np.identity(5, dtype=int) 
# this will create a 5x5 identity matrix with integer data type. The shape of the array is (5,5).

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Numpy Attributes

In [30]:
# let us create few arrays which will be used in the following examples

a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a2 = np.arange(12, dtype=float).reshape(3, 4)

# Create an array containing 12 values: 0.0 to 11.0
# Convert values to float
# Reshape into 3 rows and 4 columns

a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [32]:
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
# ndim stands for number of dimensions
# shape is the size of each dimension
# size is the total number of elements in the array

a1.ndim

1

In [34]:
a2.ndim

2

In [35]:
a3.ndim

# This will return 3 because a3 is a 3D array, i.e. it has three dimensions. 

3

In [36]:
# shape

# This will return the shape of the array, i.e. the size of each dimension.

a1.shape

(10,)

In [37]:
a2.shape

(3, 4)

In [38]:
a3.shape

# this will return (2,2,2) because a3 is a 3D array with 2 rows, 2 columns, and 2 layers.

(2, 2, 2)

In [39]:
# size 

# this will return the total number of elements in the array.

a1.size

10

In [40]:
a2.size

12

In [41]:
a3.size

8

In [42]:
# itemsize

# this will return the size of each element in bytes.

a1.itemsize

8

In [43]:
a2.itemsize

8

In [44]:
a3.itemsize

8

In [45]:
# dtype

# this will return the data type of the elements in the array.

In [46]:
a1.dtype

dtype('int64')

In [47]:
a2.dtype

dtype('float64')

In [48]:
a3.dtype

dtype('int64')

In [49]:
# astype()

a1.astype(float) # this will convert the data type of the elements in the array to float.
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
print(type(a1))

# how can i check the data type of the elements in the array?

print(a1.dtype)

# the out is int64 but we already changed to float through astype() function. Why?
# The astype() function returns a new array with the desired data type, it does not modify the original array in place.

a4 = a1.astype(float)
print(a4)
print(a4.dtype)

<class 'numpy.ndarray'>
int64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [51]:
a2.astype(int) # this will convert the data type of the elements in the array to int.
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [52]:
a5 = a2.astype(int) 
print(a5)
print(type(a5))
print(a5.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<class 'numpy.ndarray'>
int64


In [53]:
# Now let us see in the same array itself how we can change the data type of the elements in the array to float or int.
a1.astype(np.float32)
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [54]:
# We will use the below arrays as examples for our future examples.

scalar_a1 = np.arange(12).reshape(3, 4) # this will create a 3x4 array of integers from 0 to 11. The shape of the array is (3,4).
scalar_a2 = np.arange(12,24).reshape(3, 4) # this will create a 3x4 array of floats from 12 to 24. The shape of the array is (3,4).

In [55]:
scalar_a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
scalar_a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
# there are two types of operations that can be performed on numpy arrays:

# scalar operations - done with a single value, e.g. addition, subtraction, multiplication, division, etc. 

# vector operations - done with two or more arrays, e.g. addition, subtraction, multiplication, division, etc.


In [58]:
# SCALAR arithmetic operations on numpy arrays

2 * scalar_a1

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [59]:
2 * scalar_a2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [60]:
scalar_a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [61]:
scalar_a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [62]:
scalar_a2 - 3

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [63]:
scalar_a2 + 10

array([[22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [64]:
scalar_a1 % 5

array([[0, 1, 2, 3],
       [4, 0, 1, 2],
       [3, 4, 0, 1]])

In [65]:
# SCALAR relational operations on numpy arrays
# relational operators include: ==, !=, <, >, <=, >=

# The below relational operation will check each element of the array and return a boolean array with True or False.

scalar_a2 > 15


array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [66]:
scalar_a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [67]:
scalar_a2 != 15

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
# VECTOR arithmetic operations on numpy arrays

# Vector openations are performed element-wise between two arrays of the same shape. 
# If the shapes of the arrays are not the same, NumPy will try to broadcast them to a common shape.  

# broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations.
# It will automatically expand the smaller array to match the shape of the larger array, without making copies of the data.

scalar_a2 + scalar_a1

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [69]:
scalar_a2 - scalar_a1

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [70]:
scalar_a1 * scalar_a2

# this is not like matrix multiplication, it is element-wise multiplication.

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [71]:
scalar_a2 ** scalar_a1

array([[              1,              13,             196,
                   3375],
       [          65536,         1419857,        34012224,
              893871739],
       [    25600000000,    794280046581,  26559922791424,
        952809757913927]])

In [72]:
# max

np.max(scalar_a1) # this will return the maximum value in the array.

print(np.max(scalar_a1))

11


In [73]:
np.max(scalar_a2) # this will return the maximum value in the array.

np.int64(23)

In [74]:
# min

np.min(scalar_a1) # this will return the minimum value in the array.

np.int64(0)

In [75]:
np.min(scalar_a2) # this will return the minimum value in the array.

np.int64(12)

In [76]:
# sum

# This will return the sum of all the elements in the array.

print(np.sum(scalar_a1))

66


In [77]:
print(np.sum(scalar_a2))

210


In [78]:
# prod  

# This will multiply all the elements in the array and return the product.

print(np.prod(scalar_a1)) # this will return the product of all the elements in the array.


0


In [79]:
print(np.prod(scalar_a2)) # this will return the product of all the elements in the array.

647647525324800


In [80]:
# mean

# This will return the mean of all the elements in the array.

print(np.mean(scalar_a1)) # this will return the mean of all the elements in the array.    


5.5


In [81]:
print(np.mean(scalar_a2)) # this will return the mean of all the elements in the array. 

17.5


In [82]:
# Row-wise: find max, min, sum or mean or product of each row in the array.

print(scalar_a1) # just to see the array again 

print(np.max(scalar_a1, axis=1)) # this will return the maximum value of each row in the array.

# axis = 0 means column-wise operation, i.e. it will return the maximum value of each column in the array.
# axis = 1 means row-wise operation, i.e. it will return the maximum value of each row in the array.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 3  7 11]


In [83]:
print(scalar_a2) # just to see the array again

print(np.min(scalar_a2, axis=1)) # this will return the minimum value of each row in the array.


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[12 16 20]


In [84]:
print(np.min(scalar_a1, axis=1)) # this will return the minimum value of each row in the array.

[0 4 8]


In [85]:
np.sum(scalar_a1, axis=1) # this will return the sum of each row in the array.

array([ 6, 22, 38])

In [86]:
# mean

print(np.mean(scalar_a1)) # this will return the mean of all the elements in the array.

5.5


In [87]:
# median 

print(np.median(scalar_a1)) # this will return the median of all the elements in the array.

# we see that median and mean are same in this case because the array is evenly distributed.

5.5


In [88]:
# mean

print(np.mean(scalar_a2)) # this will return the mean of all the elements in the array.

17.5


In [89]:
# median

print(np.median(scalar_a2)) # this will return the median of all the elements in the array. 

# we again see that mean and median are same in this case because the array is evenly distributed.

17.5


In [90]:
# row-wise or column-wise mean or median

# this can be done by just writing axis=0 for column-wise and axis=1 for row-wise in the mean() or median() function.

print(np.mean(scalar_a1, axis=0)) # this will return the mean of each column in the array.

print(np.mean(scalar_a1, axis=1)) # this will return the mean of each row in the array.

# first one has four values while second one has three values because there are four columns and three rows in the array.


[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [91]:
# variance 

print(np.var(scalar_a2)) # this will return the variance of all the elements in the array.

11.916666666666666


In [92]:
# standard deviation

print(np.std(scalar_a2)) # this will return the standard deviation of all the elements in the array.

3.452052529534663


In [93]:
# trigonometric functions

np.sin(scalar_a1) # this will return the sine of each element in the array.

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [94]:
np.cos(scalar_a1) # this will return the cosine of each element in the array.


array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]])

In [95]:
np.round(np.tan(scalar_a1), decimals=2) # this will return the tangent of each element in the array rounded to 2 decimal places.  

array([[ 0.0000e+00,  1.5600e+00, -2.1900e+00, -1.4000e-01],
       [ 1.1600e+00, -3.3800e+00, -2.9000e-01,  8.7000e-01],
       [-6.8000e+00, -4.5000e-01,  6.5000e-01, -2.2595e+02]])

In [96]:
# round()

# this will round the elements of the array to the nearest integer.

round(532.256898785) 

# this will round the number to the nearest integer, i.e. 532, because by default, the round() function rounds to the nearest integer.

532

In [97]:
# round() to three decimal places

round(532.256898785, ndigits = 3) # this will round the number to three decimal places, i.e. 532.257.


532.257

In [98]:

# if we do the same using np.round() function, it will return a numpy array instead of a single value.

np.round(np.array([532.256898785]), decimals = 3) # this will round the number to three decimal places, i.e. 532.257 and return a numpy array.

array([532.257])

In [99]:
# dot product

# what is this and how is it compared to matrix multiplication we learnt in math classes?

dot_prod_a1_a2 = np.dot(scalar_a1, scalar_a2.T) # this will return the dot product of two arrays. 

# The second array is transposed to match the shape of the first array.

dot_prod_a1_a2


array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

In [100]:
# log

np.log(scalar_a1) # this will return the natural logarithm of each element in the array.    

/var/folders/hw/hxflgr3n1cz4qg8ymp_fml840000gn/T/ipykernel_7673/1353821573.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(scalar_a1) # this will return the natural logarithm of each element in the array.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [101]:
# exponential function

np.exp(scalar_a1) # this will return the exponential of each element in the array.

# the above code is doing the same as np.e ** scalar_a1, i.e. it is raising e to the power of each element in the array. 
# For example, np.exp(1) will return e^1 = 2.718281828459045, which is the value of e.


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [102]:
# exponential function with base 10 means 10 raised to the power of each element in the array.
np.power(10, scalar_a1) # this will return 10 raised to the power of each element in the array. 

array([[           1,           10,          100,         1000],
       [       10000,       100000,      1000000,     10000000],
       [   100000000,   1000000000,  10000000000, 100000000000]])

In [103]:
# np.random()

np.random.random()

0.9967633584162222

In [104]:
np.round(np.random.random((3,4)), 2)*1000 

# this will return a 3x4 array of random numbers between 0 and 1, rounded to 2 decimal places.



array([[ 30., 180.,  40., 570.],
       [820., 190., 900., 450.],
       [730., 100., 590., 840.]])

In [105]:
# np.floor()

np.floor(52525.2365)

np.float64(52525.0)

In [106]:
# np.ceil()
 
np.ceil(52525.2365)

np.float64(52526.0)

# NumPy Indexing and Slicing (difficult topic)

In [107]:
a6 = np.arange(10)
a6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
a7 = np.arange(12).reshape(3, 4)
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a8 = np.arange(8).reshape(2,2,2)
a8

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [110]:
# how to get last item from a7 array? in python and in numpy?

# in python

print([a1.size -1]) # this will return the last item in the array a1.

[9]


In [111]:
print(a6[-1]) # this will return the last item in the array a7.

9


In [112]:
# just to see a7 array_2D
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
print(a7[0])

[0 1 2 3]


In [114]:
print(a7[-1])

[ 8  9 10 11]


In [115]:
# how to fetch 11

a7[2,3] # this will return the element at row 2 and column 3 in the array a7, which is 11.

np.int64(11)

In [116]:
# how to fetch 6

a7[1,2] # this will return the element at row 1 and column 2 in the array a7, which is 6.

np.int64(6)

In [117]:
# Just to see a8 array_3D
a8

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [118]:
a8[0]

array([[0, 1],
       [2, 3]])

In [119]:
a8[1]

array([[4, 5],
       [6, 7]])

In [120]:
a8[1,0] # this will return the first element of the second layer in the array a8, which is 4000.

array([4, 5])

In [122]:
a8[1,1]

array([6, 7])

In [123]:
# just to see the array a8 again
a8

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [125]:
# how to fetch 7 from the array a8?

print(a8[1,1,1])

7


In [128]:
# how to fetch 5 from the array a8?

print(a8[1,0,1])

5


In [129]:
# how to fetch 4 from the array a8?

print(a8[1,0,0])

4


Studied until min 1 hr and min 17