# Why Numpy?

NumPy is built in C language because C is faster while Python is slower. On the other hand, syntax of Python is easier to learn and hence it became very famous among users (especially non-programming or developer).

Pandas, matplotlib, etc. are then built on NumPy. This made Numpy an excellency choice for Data Science field.

# Numpy Array vs Python Sequences

1. NumPy arrays have fixed size at creation, unlike Python lists (which can grow dynamically). If you change size of an ndarray it will create a new array and delete the original one.

2. NumPy array have one datatype, i.e. Homegenous, while lists are heterogeneous and can contain different datatypes. 

Note: Python lists are able to store different types of data because they store pointers (addresses) to the actual data rather than the data itself. This allows lists to be flexible and store various types of data. However, this means that they require more memory and are slower for numerical operations compared to NumPy arrays, which store data in a contiguous block of memory and are optimized for performance.

3. NumPy arrays are more compact than lists, which means they use less memory to store data. This is because NumPy arrays are stored in a contiguous block of memory, while lists store pointers to the actual data.

4. NumPy arrays are faster than lists for numerical operations because they are optimized for performance and use less memory. This is because NumPy arrays are implemented in C and use optimized algorithms for numerical operations, while lists are implemented in Python and are not optimized for performance.

5. NumPy arrays have a wide range of built-in functions and methods for performing mathematical operations, while lists do not have as many built-in functions for numerical operations. This makes NumPy arrays more convenient for scientific computing and data analysis tasks.

6. NumPy arrays support vectorized operations, which means you can perform element-wise operations on entire arrays without the need for explicit loops. This allows for more efficient and concise code when performing mathematical operations on large datasets.

7. NumPy arrays can be multi-dimensional, allowing for the creation of matrices and higher-dimensional arrays, while Python lists are typically one-dimensional (though they can contain other lists to create multi-dimensional structures, it is not as efficient or convenient as using NumPy arrays).

8. NumPy arrays have a fixed size at creation, while Python lists can grow dynamically. If you change the size of a NumPy array, it will create a new array and delete the original one, while Python lists can simply append or remove elements without creating a new list.

9. A growing number of libraries and frameworks in the scientific computing and data science ecosystem are built on top of NumPy, making it a fundamental tool for many applications in these fields. This widespread adoption has further solidified NumPy's position as a key component of the Python scientific computing stack.


In [4]:
# import libraries

# np = numerical python

# np is just a shortform for numpy library
 

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [ ]:
# create list of numbers in NumPy array

# this is a 1D array, i.e. one dimensional array

array_1D = np.array([1,2,3,4,5,6,7,8,9,10])

print(array_1D)
print(type(array_1D))


[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


1. The type of the array says <class 'numpy.ndarray'>

2. Class is a blueprint for creating objects. This is a famous concept in object-oriented programming (OOP). 

3. Python is an object-oriented programming language, which means that it allows you to create and use objects.

4. Everything in Python is an object, including functions, classes, and even modules.

# Types of Numerical Data Structures

Scalar  = one number
Vector  = list of numbers
Matrix  = table of numbers
Tensor  = any higher-dimensional collection of numbers including 3D

0D → Scalar
1D → Vector
2D → Matrix
3D+ → Tensor

In [8]:
# let us create a 2D array, i.e. two dimensional array such as a matrix

array_2D = np.array([[100,101],
                     [102,103],
                     [104,105],
                     [106,107],
                     [108,109]
                     ]) 

print(array_2D)
print(type(array_2D))
print(array_2D.shape) # this will give us the shape of the array, i.e. number of rows and columns


[[100 101]
 [102 103]
 [104 105]
 [106 107]
 [108 109]]
<class 'numpy.ndarray'>
(5, 2)


In [13]:
# let us create a 3D array, i.e. three dimensional array such as a tensor.

# Tensor is a generalization of matrices to higher dimensions. It is a multi-dimensional array.

array_3D = np.array([
                    [
                        [1000,2000],
                        [1500,2500]
                    ],
                    [
                        [4000,5000],
                        [4500,5500]     
                    ],
                    [
                        [6000,7000],
                        [6500,7500]
                    ]
                    ])

print(array_3D)
print(type(array_3D))
print(array_3D.shape) 


[[[1000 2000]
  [1500 2500]]

 [[4000 5000]
  [4500 5500]]

 [[6000 7000]
  [6500 7500]]]
<class 'numpy.ndarray'>
(3, 2, 2)


Studied until min 18