# Advanced Numpy

In [1]:
import numpy as np
import pandas as pd
# Why Numpy Array is preferred over Python List?
#   1. speed
#   2. memory consumption
#   3. convenience

# speed comparison between Python List and Numpy Array.

a = [i for i in range(10000000)]    # this is a Python List of 10 million integers starting from 0 to 9999999

b = [i for i in range(10000000, 20000000)]  # this is a Python List of 10 million integers starting from 10000000 to 19999999

# now we will add these two lists using Python List comprehension and measure the time taken for this operation.

c = []

# we need to record the time taken for this operation, so we will use the time module.
# so we will see the time before the loop starts and after the loop ends.

# current time is 'start'

import time

start = time.time()    # this will record the current time before the loop starts

for i in range(len(a)):      # len(a) and len(b) are both 10 million, so this loop will run 10 million times.
    c.append(a[i] + b[i])    # adding the corresponding elements of the two lists and appending to the new list c

time_taken_list = time.time() - start    # this will record the time after the loop ends and calculate the time taken for the operation

print(a[100])
print(b[100])
print(c[100])
print("Time taken by Python List:", time_taken_list)    # this will print the time taken for the operation in seconds


100
10000100
10000200
Time taken by Python List: 0.7562251091003418


In [2]:
# use Numpy Array to perform the same operation and measure the time taken for this operation.

a = np.arange(10000000)    # this is a Numpy Array of 10 million integers starting from 0 to 9999999
b = np.arange(10000000, 20000000)  # this is a Numpy Array of 10 million integers starting from 10000000 to 19999999

start_Numpy = time.time()    # this will record the current time before the operation

c = a + b    # adding the two Numpy Arrays

time_taken_Numpy = time.time() - start_Numpy    # this will record the time after the operation and calculate the time taken for the operation

print(a[100])
print(b[100])
print(c[100])
print("Time taken by Numpy Array:", time_taken_Numpy)    # this will print the time taken for the operation in seconds

time_taken_Numpy

100
10000100
10000200
Time taken by Numpy Array: 0.06187176704406738


0.06187176704406738

In [3]:
# Compare time taken by Numpy vs Python List for the same operation.

time_taken_list/time_taken_Numpy

# Two reasons why Numpy Array is faster than Python List:

# 1. Numpy Arrays are implemented in C and optimized for performance, 
#   while Python Lists are implemented in Python and have more overhead.  

# 2. Numpy Arrays are homogeneous, meaning they can only contain elements of the same data type, 
#    which allows for more efficient memory usage and faster computations. 
#    Python Lists can contain elements of different data types, which adds overhead and slows down operations.    


12.222458565984224

In [4]:
# Memory

# Now let us see how much memoryview is consumed by Python List and Numpy Array for the same data.

a = [i for i in range(10000000)]    # this is a Python List of 10 million integers starting from 0 to 9999999
import sys
size_a = sys.getsizeof(a)    # this will return the size of the Python List in bytes
size_a

89095160

In [5]:
b = np.arange(10000000)    # this is a Numpy Array of 10 million integers starting from 0 to 9999999
size_b = b.nbytes    # this will return the size of the Numpy Array in bytes
size_b

80000000

In [6]:
# Difference in memory consumption between Python List and Numpy Array for the same data.

size_a / size_b

# They are almost same. 
# However, we can reduce the memory consumption of Numpy Array by changing the data type of the array to a smaller data type.

1.1136895

In [7]:
# let us create a Numpy Array of 10 million integers starting from 0 to 9999999 with data type int32 instead of int64 (default data type for Numpy Array).
revised_a = np.arange(10000000, dtype=np.int32)
size_revised_a = revised_a.nbytes
size_revised_a

40000000

In [8]:
from numpy import half


size_a / size_revised_a

# we reduced the size to half by changing the data type of the Numpy Array to int32 instead of int64.

2.227379

In [9]:
# we can further reduce by changing data type to int16 or int8, 
# but we need to be careful about the range of values we are storing in the array. 
# If the values exceed the range of the data type, it will lead to overflow and incorrect results.

# remember: 
# range of int8 is -128 to 127
# range of int16 is -32768 to 32767
# range of int32 is -2147483648 to 2147483647
# range of int64 is -9223372036854775808 to 9223372036854775807

In [10]:
# just let us see how int8 can make problem for us.

a_int8 = np.arange(1000, dtype=np.int8)
a_int8

# As you can see, it reached 127 and then went straight to -128 and then started increasing again. 
# This is because the range of int8 is -128 to 127, and when it exceeds 127, it wraps around to -128. 
# This is called overflow.

# Same is in int16 also. As soon as it reaches 32767, it will wrap around to -32768. 


array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127, -128, -127, -126, -125,
       -124, -123, -122, -121, -120, -119, -118, -117, -116, -115, -114,
       -113, -112, -111, -110, -109, -108, -107, -1

In [11]:
max(a_int8)

np.int8(127)

In [12]:
min(a_int8)

np.int8(-128)

In [13]:
# Convenience
# Let us see how convenient it is to use Numpy Array over Python List for mathematical operations.

# no loop was created in above Numpy Array addition operation, 
# while in Python List addition operation, we had to create a loop to add the corresponding elements of the two lists.

In [14]:
# two new ways of indexing in Numpy Array are Boolean Indexing and Fancy Indexing

# we create array_a which we will use in Boolean Indexing and Fancy Indexing examples

array_a = np.arange(12).reshape(4, 3)    # this will create a 2D Numpy Array of shape (3, 4) with values from 0 to 11

array_a




array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
# # Fancy Indexing (when you can't use any pattern)

# Fancy Indexing allows you to select elements from an array using integer arrays.

# fetch first, third and fourth rows of array_a. You cannot do this using slicing, but you can do this using Fancy Indexing.
# You cannot do this using slicing because slicing only allows you to select a range of rows or columns, not specific ones.

# In fancy indexing, you can pass a list or an array of integers to select specific rows or columns from the array.

array_a[[0, 2, 3]]  # Fancy Indexing to fetch first, third and fourth rows


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
# fetch all rows

array_a[:]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
# fetch all rows but only first column
array_a[:, [0]]

array([[0],
       [3],
       [6],
       [9]])

In [27]:
# fetch all columns but only row 1 and 3
array_a[[1,3], :]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [21]:
# another example of fancy indexing is to fetch first and third columns of array_a. 
# You cannot do this using slicing, but you can do this using Fancy Indexing.
array_a[:, [0, 2]]  # Fancy Indexing to fetch first and third columns

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [29]:
array_b = np.arange(24).reshape(6, 4)    
array_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
# fetch 1st, 3rd, 4th row and 6th row.

array_b[[0,2,3,5], :]  # Fancy Indexing to fetch 1st, 3rd, 4th and 6th rows

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [32]:
# fetch 1st column, 3rd and 4th column.

array_b[:, [0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [16]:
# Boolean Indexing

# Studied until min 28