# Advanced Numpy

In [1]:
import numpy as np
import pandas as pd
# Why Numpy Array is preferred over Python List?
#   1. speed
#   2. memory consumption
#   3. convenience

# speed comparison between Python List and Numpy Array.

a = [i for i in range(10000000)]    # this is a Python List of 10 million integers starting from 0 to 9999999

b = [i for i in range(10000000, 20000000)]  # this is a Python List of 10 million integers starting from 10000000 to 19999999

# now we will add these two lists using Python List comprehension and measure the time taken for this operation.

c = []

# we need to record the time taken for this operation, so we will use the time module.
# so we will see the time before the loop starts and after the loop ends.

# current time is 'start'

import time

start = time.time()    # this will record the current time before the loop starts

for i in range(len(a)):      # len(a) and len(b) are both 10 million, so this loop will run 10 million times.
    c.append(a[i] + b[i])    # adding the corresponding elements of the two lists and appending to the new list c

time_taken_list = time.time() - start    # this will record the time after the loop ends and calculate the time taken for the operation

print(a[100])
print(b[100])
print(c[100])
print("Time taken by Python List:", time_taken_list)    # this will print the time taken for the operation in seconds


100
10000100
10000200
Time taken by Python List: 0.6587250232696533


In [2]:
# use Numpy Array to perform the same operation and measure the time taken for this operation.

a = np.arange(10000000)    # this is a Numpy Array of 10 million integers starting from 0 to 9999999
b = np.arange(10000000, 20000000)  # this is a Numpy Array of 10 million integers starting from 10000000 to 19999999

start_Numpy = time.time()    # this will record the current time before the operation

c = a + b    # adding the two Numpy Arrays

time_taken_Numpy = time.time() - start_Numpy    # this will record the time after the operation and calculate the time taken for the operation

print(a[100])
print(b[100])
print(c[100])
print("Time taken by Numpy Array:", time_taken_Numpy)    # this will print the time taken for the operation in seconds

time_taken_Numpy

100
10000100
10000200
Time taken by Numpy Array: 0.05577397346496582


0.05577397346496582

In [3]:
# Compare time taken by Numpy vs Python List for the same operation.

time_taken_list/time_taken_Numpy

# Two reasons why Numpy Array is faster than Python List:

# 1. Numpy Arrays are implemented in C and optimized for performance, 
#   while Python Lists are implemented in Python and have more overhead.  

# 2. Numpy Arrays are homogeneous, meaning they can only contain elements of the same data type, 
#    which allows for more efficient memory usage and faster computations. 
#    Python Lists can contain elements of different data types, which adds overhead and slows down operations.    


11.810616715042341

In [4]:
# Memory

# Now let us see how much memoryview is consumed by Python List and Numpy Array for the same data.

a = [i for i in range(10000000)]    # this is a Python List of 10 million integers starting from 0 to 9999999
import sys
size_a = sys.getsizeof(a)    # this will return the size of the Python List in bytes
size_a

89095160

In [5]:
b = np.arange(10000000)    # this is a Numpy Array of 10 million integers starting from 0 to 9999999
size_b = b.nbytes    # this will return the size of the Numpy Array in bytes
size_b

80000000

In [6]:
# Difference in memory consumption between Python List and Numpy Array for the same data.

size_a / size_b

# They are almost same. 
# However, we can reduce the memory consumption of Numpy Array by changing the data type of the array to a smaller data type.

1.1136895

In [7]:
# let us create a Numpy Array of 10 million integers starting from 0 to 9999999 with data type int32 instead of int64 (default data type for Numpy Array).
revised_a = np.arange(10000000, dtype=np.int32)
size_revised_a = revised_a.nbytes
size_revised_a

40000000

In [8]:
from numpy import half


size_a / size_revised_a

# we reduced the size to half by changing the data type of the Numpy Array to int32 instead of int64.

2.227379

In [9]:
# we can further reduce by changing data type to int16 or int8, 
# but we need to be careful about the range of values we are storing in the array. 
# If the values exceed the range of the data type, it will lead to overflow and incorrect results.

# remember: 
# range of int8 is -128 to 127
# range of int16 is -32768 to 32767
# range of int32 is -2147483648 to 2147483647
# range of int64 is -9223372036854775808 to 9223372036854775807

In [10]:
# just let us see how int8 can make problem for us.

a_int8 = np.arange(1000, dtype=np.int8)
a_int8

# As you can see, it reached 127 and then went straight to -128 and then started increasing again. 
# This is because the range of int8 is -128 to 127, and when it exceeds 127, it wraps around to -128. 
# This is called overflow.

# Same is in int16 also. As soon as it reaches 32767, it will wrap around to -32768. 


array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127, -128, -127, -126, -125,
       -124, -123, -122, -121, -120, -119, -118, -117, -116, -115, -114,
       -113, -112, -111, -110, -109, -108, -107, -1

In [11]:
max(a_int8)

np.int8(127)

In [12]:
min(a_int8)

np.int8(-128)

In [13]:
# Convenience
# Let us see how convenient it is to use Numpy Array over Python List for mathematical operations.

# no loop was created in above Numpy Array addition operation, 
# while in Python List addition operation, we had to create a loop to add the corresponding elements of the two lists.

In [14]:
# two new ways of indexing in Numpy Array are Boolean Indexing and Fancy Indexing

# we create array_a which we will use in Boolean Indexing and Fancy Indexing examples

array_a = np.arange(12).reshape(4, 3)    # this will create a 2D Numpy Array of shape (3, 4) with values from 0 to 11

array_a




array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
# # Fancy Indexing (when you can't use any pattern)

# Fancy Indexing allows you to select elements from an array using integer arrays.

# fetch first, third and fourth rows of array_a. You cannot do this using slicing, but you can do this using Fancy Indexing.
# You cannot do this using slicing because slicing only allows you to select a range of rows or columns, not specific ones.

# In fancy indexing, you can pass a list or an array of integers to select specific rows or columns from the array.

array_a[[0, 2, 3]]  # Fancy Indexing to fetch first, third and fourth rows


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
# fetch all rows

array_a[:]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
# fetch all rows but only first column
array_a[:, [0]]

array([[0],
       [3],
       [6],
       [9]])

In [18]:
# fetch all columns but only row 1 and 3
array_a[[1,3], :]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [19]:
# another example of fancy indexing is to fetch first and third columns of array_a. 
# You cannot do this using slicing, but you can do this using Fancy Indexing.
array_a[:, [0, 2]]  # Fancy Indexing to fetch first and third columns

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [20]:
array_b = np.arange(24).reshape(6, 4)    
array_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
# fetch 1st, 3rd, 4th row and 6th row.

array_b[[0,2,3,5], :]  # Fancy Indexing to fetch 1st, 3rd, 4th and 6th rows

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [22]:
# fetch 1st column, 3rd and 4th column.

array_b[:, [0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [23]:
# Boolean Indexing

# we dont need always to use an index to fetch the data from an array. 
# We can also use a "condition" or "logic" to fetch the data from an array. This is called Boolean Indexing.

d = np.random.randint(1,100,24).reshape(6,4)   # this will create a 2D Numpy Array of shape (6, 4) with random integers between 1 and 100 
d

array([[94,  3, 39, 71],
       [73, 25, 73,  7],
       [50, 83, 75, 59],
       [54, 29, 27, 31],
       [48, 17,  6, 85],
       [86, 27, 87, 54]])

In [24]:
d > 70   
# this will return a boolean array of the same shape as array_bool_ind_a, 
# where each element is True if the corresponding element in array_bool_ind_a is greater than 50, and False otherwise.

array([[ True, False, False,  True],
       [ True, False,  True, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True, False,  True, False]])

In [25]:
# we can use this boolean array as a "mask" to fetch the elements from the original array that satisfy the condition.

# Only true values will be fetched from the original array, and false values will be ignored.

d[d > 70]

array([94, 71, 73, 73, 83, 75, 85, 86, 87])

In [26]:
# Boolean indexing (e.g. Fetch odd/even numbers)

d[d % 2 == 0]   
# this will return all the even numbers from the array_bool_ind_a 

array([94, 50, 54, 48,  6, 86, 54])

In [27]:
# boolean indexing (e.g. Fetch even numbers which are greater than 50)
d[(d % 2 == 0) & (d > 50)]

array([94, 54, 86, 54])

In [28]:
# Why we used "&" instead of "and" in the above example?
# because "and" is a logical operator that works on boolean values, while "&" is a bitwise operator that works on binary values.
# in the above example, we are using "&" to combine two boolean arrays, which is a bitwise operation.

# to remember:
# "and" is a logical operator that works on boolean values, while "&" is a bitwise operator that works on binary values. 
# in the above example, we are using "&" to combine two boolean arrays, which is a bitwise operation.



In [29]:
# find numbers divisible by 7

d[(d % 7 == 0)]

array([7])

In [30]:
# find numbers not divisible by 7
d[(d%7 != 0)]

array([94,  3, 39, 71, 73, 25, 73, 50, 83, 75, 59, 54, 29, 27, 31, 48, 17,
        6, 85, 86, 27, 87, 54])

In [31]:
# another way it to put "not" operator in front of the condition, i.e. 
d[~(d % 7 == 0)]

array([94,  3, 39, 71, 73, 25, 73, 50, 83, 75, 59, 54, 29, 27, 31, 48, 17,
        6, 85, 86, 27, 87, 54])

# Broadcasting

A very important but confusing topic.

In [32]:
# Broadcasting

# This technique allows you to perform operations on arrays of different shapes and sizes, 
# without the need for explicit looping or reshaping.

In [33]:
# The term "broadcasting" refers to the ability of Numpy to perform arithmetic operations on arrays of different shapes and sizes,
# by "stretching" the smaller array to match the shape of the larger array,
# without actually copying the data in memory. 

# This is done by "broadcasting" the smaller array across the larger array, 
# so that they have compatible shapes for the operation.


In [34]:
# same shape

e = np.arange(6).reshape(2, 3)    # this will create a 2D Numpy Array of shape (2, 3) with values from 0 to 5

f = np.arange(6,12).reshape(2, 3)    # this will create a 2D Numpy Array of shape (2, 3) with values from 6 to 11

In [35]:
e

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
f

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
# e and f have the same shape, so we can perform arithmetic operations on them without any issues.

In [38]:
e+f

array([[ 6,  8, 10],
       [12, 14, 16]])

In [39]:
e-f

array([[-6, -6, -6],
       [-6, -6, -6]])

In [40]:
e*f

array([[ 0,  7, 16],
       [27, 40, 55]])

In [41]:
e/f

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [42]:
e%f

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
# different shape

g = np.arange(6).reshape(2, 3)    # this will create a 2D Numpy Array of shape (2, 3) with values from 0 to 5

h = np.arange(3).reshape(1, 3)    # this will create a 2D Numpy Array of shape (1, 3) with values from 6 to 11

In [44]:
g

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
h

array([[0, 1, 2]])

In [46]:
# can we add these two arrays of different shapes? 
# Yes, we can add these two arrays of different shapes using broadcasting.

# in normal mathematics, we cannot add two matrices of different shapes.

g + h  

# this will work in Numpy due to broadcasting
# what Numpy will do is that it will "stretch" the smaller array h to match the shape of the larger array g,
# by repeating the values of h along the first axis, so that they have compatible shapes for the operation.

array([[0, 2, 4],
       [3, 5, 7]])

In [47]:
# In the above example, the row 0,1,2 was replicated in second row to match the shape of the larger array g, 
# so that they have compatible shapes for the operation.

In [48]:
# Three rules of broadcasting:

# 1. Make the two arrays have the same number of dimensions by adding new dimensions of size 1 to the smaller array, if necessary.
 
# 2. If the shape of the two arrays does not match in any dimension, 
#    the array with shape equal to 1 in that dimension is stretched to match the other shape.

# 3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.



In [49]:
# Understand Rule 1 of broadcasting:

# For example, you have 2D array of shape (3,2) and 1D array of shape (3,). 
# According to Rule 1, you need to reshape the 1D array to (1,3) before broadcasting.
# So the 1D array will become a 2D array of shape (1,3) by repeating the values along the first axis.

# For example, you have a 3D array of shape (3,3,3) and 1D array of shape (3,).
# According to Rule 1, 
#      you need to reshape the 1D array to (1,1,3) before broadcasting, 
#      i.e. 1 is added to the "head" of the shape of the 1D array to make it compatible with the 3D array.
#      So the 1D array will become a 3D array of shape (1,1,3) by repeating the values along the first and second axes.


In [50]:
# Rule 2 of broadcasting:

# According to Rule 2, if the shape of the two arrays does not match in any dimension,
# the array with shape equal to 1 in that dimension is stretched to match the other shape.

# Rule 3 of broadcasting: 
# Error is raised (broadcasting fails) if in any dimension the sizes disagree and neither is equal to 1.


In [56]:
# Example: Broadcasting

i = np.arange(12).reshape(4,3)    # this will create a 2D Numpy Array of shape (4, 3) with values from 0 to 11

j = np.arange(3)    # this will create a 2D Numpy Array of shape (1, 3) with values from 0 to 2


print("Array i is:\n", i)
print("\n\nArray j is:\n", j)

Array i is:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Array j is:
 [0 1 2]


In [ ]:
sum_i_j = i+j

sum_i_j

# what happened actually?

# j became:
# [[0, 1, 2],
#  [0, 1, 2],
#  [0, 1, 2],
#  [0, 1, 2]]

# then it was added to i

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [53]:
# So, i array is of shape (4,3) and j array is of shape (1,3).

# Now, you can broadcast j array to i array.

# how this will work?
# Step 1: add a new dimension of size 1 to the smaller array j, so that it becomes a 2D array of shape (1,3).

# Step 2: Broadcast the 1 to 4, and we get new size of j array as (4,3).

# Check: are the shapes same? 
# if yes, then we can perform arithmetic operations on these two arrays of different shapes using broadcasting.

# Yes, because we get new size of j array as (4,3) after broadcasting, which is same as the size of i array.

# Now, you will be able to do arithmetic operations on these two arrays of different shapes using broadcasting.

In [59]:
# Modifying above example: Broadcasting

k = np.arange(12).reshape(3,4)    # this will create a 2D Numpy Array of shape (3, 4) with values from 0 to 11

l = np.arange(3)    # this will create a 2D Numpy Array of shape (1, 3) with values from 0 to 2

print("Array k is:\n", k)
print("\n\nArray l is:\n", l)

Array k is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array l is:
 [0 1 2]


In [64]:
# k+l will give error
# broadcasting will not work in this case because the shapes of the two arrays are not compatible for broadcasting.

# what happened actually? 

# j became:
# [[0, 1, 2],
#  [0, 1, 2],
#  [0, 1, 2]]

# The steps followed by j are:
# Step 1: add a new dimension of size 1 to the smaller array l, so that it becomes a 2D array of shape (1,3).
# Step 2: Broadcast the 1 to 3, and we get new size of l array as (3,3).
# Check: are the shapes same?
# if yes, then we can perform arithmetic operations on these two arrays of different shapes using broadcasting 
# if no, then we cannot perform arithmetic operations on these two arrays of different shapes using broadcasting.

In [65]:
# Third example: Broadcasting

# Modifying above example: Broadcasting

m = np.arange(3).reshape(1,3)    # this will create a 2D Numpy Array of shape (1, 3) with values from 0 to 2

n = np.arange(3).reshape(3,1)    # this will create a 2D Numpy Array of shape (1, 3) with values from 3 to 5

print("Array m is:\n", m)
print("\n\nArray n is:\n", n)

Array m is:
 [[0 1 2]]


Array n is:
 [[0]
 [1]
 [2]]


In [ ]:
# So, we have (1,3) and (3,1) of 2D shapes.
# We can break this down into 3 steps to see how broadcasting will work in this case.
# Step 1: add a new dimension of size 1 to the smaller array m, so that it becomes a 2D array of shape (1,3).
# Step 2: Broadcast the 1 to 3, and we get new size of m array as (3,3).
# Step 3: Broadcast the 1 to 3, and we get new size of n array as (3,3).

In [66]:
m+n

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
# what happened actually?
# m became:
# [[0, 1, 2],
#  [0, 1, 2],
#  [0, 1, 2]]   

# n:
#[[0, 0, 0],
#  [1, 1, 1],
#  [2, 2, 2]]


In [68]:
# Fourth example: Broadcasting

# Modifying above example: Broadcasting

p = np.arange(3).reshape(1,3)    # this will create a 2D Numpy Array of shape (1, 3) with values from 0 to 2

q = np.arange(4).reshape(4,1)    # this will create a 2D Numpy Array of shape (4, 1) with values from 0 to 3

print("Array p is:\n", p)
print("\n\nArray q is:\n", q)

Array p is:
 [[0 1 2]]


Array q is:
 [[0]
 [1]
 [2]
 [3]]


In [ ]:
# both p and q are 2D arrays, but they have different shapes.

# p has shape (1, 3) and q has shape (4, 1)

# p is changed to (4,3) and q is changed to (4,3) after broadcasting. 
# That is why we can perform arithmetic operations on these two arrays of different shapes using broadcasting.

In [70]:
p + q

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

# Studied until min 55